# Generated by Django 4.2.4 on 2023-08-21 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coffee", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="coffee",
            name="caffeine",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="coffee",
            name="kcal",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="coffee",
            name="price",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="coffee",
            name="sugar",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
